name: Gralde check: Legacy

on:
  push:
    branches:
      - Legacy
  pull_request:
    branches:
      - Legacy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./gradlew :app:assembleDebug
